---
- name: Install bind9
apt:
name: bind9
state: present
update_cache: yes


- name: Ensure /etc/bind exists
file:
path: /etc/bind
state: directory
owner: root
group: root
mode: '0755'


- name: Deploy named.conf.local
template:
src: named.conf.local.j2
dest: /etc/bind/named.conf.local
owner: root
group: root
mode: '0644'
notify: restart bind


- name: Deploy zone file
template:
src: db.example.local.j2
dest: "{{ dns_zone_file }}"
owner: root
group: root
mode: '0644'
notify: restart bind


- name: Ensure bind9 enabled and started
service:
name: bind9
state: started
enabled: yes
